<pre style="font-size:14px; line-height:1.1; font-weight:bold;">
███╗   ██╗██╗   ██╗███╗   ███╗██████╗ ██╗   ██╗
████╗  ██║██║   ██║████╗ ████║██╔══██╗╚██╗ ██╔╝
██╔██╗ ██║██║   ██║██╔████╔██║██████╔╝ ╚████╔╝ 
██║╚██╗██║██║   ██║██║╚██╔╝██║██╔═══╝   ╚██╔╝  
██║ ╚████║╚██████╔╝██║ ╚═╝ ██║██║        ██║  
╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚═╝        ╚═╝  

███╗   ██╗██╗███╗   ██╗     ██╗ █████╗ 
████╗  ██║██║████╗  ██║     ██║██╔══██╗
██╔██╗ ██║██║██╔██╗ ██║     ██║███████║
██║╚██╗██║██║██║╚██╗██║██   ██║██╔══██║
██║ ╚████║██║██║ ╚████║╚█████╔╝██║  ██║
╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝ ╚════╝ ╚═╝  ╚═╝
</pre>


👋 **Welcome to _NumPy Ninja_**  

This notebook is my **personal dojo** where I sharpen my skills in **NumPy**,  
the backbone of **Data Science & Machine Learning**.

Here, I will:
- 🧠 Build **rock-solid fundamentals**
- ⚡ Explore **powerful NumPy operations**
- 🧩 Solve **real-world array problems**
- 🛠️ Write **clean, efficient, and optimized code**

---

## 🎯 Mission
To **master NumPy deeply**, not just use it —  
and to **share my learning journey** with the community.

---

## 🚀 What You’ll Find Inside
- 📌 Core NumPy concepts (from basics to advanced)
- 📌 Practical examples & visual intuition
- 📌 Performance-focused techniques
- 📌 Clean explanations for **beginners → advanced learners**

---

## 💡 Why *NumPy Ninja*?
Because NumPy isn’t just a library —  
it’s a **skill**, a **mindset**, and a **superpower** 🥷

---

## 🤝 Let’s Learn Together
If this notebook helps you, inspires you, or teaches you something new —  
feel free to **connect, share, and grow together**.

---

### ✍️ Created & Maintained by  
## **Babar Ali Mahar**  

🔗 *Sharing this journey on LinkedIn — one notebook at a time.*

---

> 🧘 *“First you understand the array.  
> Then the array understands you.”*


In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
a= [1,2.5,3.3,4,5]
arr=np.array(a)
arr
type(arr)

numpy.ndarray

In [3]:
arr = np.array(['1', 2, 3, 4, 5])  # NumPy converts all elements to strings because arrays must have a single data type
arr


array(['1', '2', '3', '4', '5'], dtype='<U21')

## Let's Create a Matrix using List

In [4]:
a =[[1,2,3],[4,5,6],[7,8,9]] # 2-D list
arr=np.array(a) #Matrix
arr 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now Let's see how matrix looks like using Numpy Arrays:

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [6]:
arr=np.zeros([12,13])
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones([5,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.full([5,7],11)

array([[11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11]])

In [9]:
np.arange(1,16)  # Just like range in Python

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.linspace(1, 10, 5)  # Generates 5 evenly spaced numbers between 1 and 10 (inclusive)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5,2) # Always values will be in between 0 and 1

array([[0.13482325, 0.36826832],
       [0.84705779, 0.28384215],
       [0.85367318, 0.41231442],
       [0.88317349, 0.51001654],
       [0.248324  , 0.95654391]])

In [13]:
np.random.randint(1, 100, (3, 3))  # Generates a 3×3 array of random integers from 1 (inclusive) to 100 (exclusive)


array([[18, 51, 85],
       [73, 67, 21],
       [84, 37, 29]], dtype=int32)

In [14]:
np.random.randn(2,4)  # random numbers from a standard normal distribution (mean=0, std=1)

array([[-1.52829803,  0.45785642,  0.3470021 , -0.55018197],
       [-1.91960599,  0.19928965,  0.54845078, -0.12997037]])

np.arange()        # step-based values  
np.linspace()      # fixed number of values  
np.eye()           # identity matrix  
np.random.rand()   # random floats (0–1)  
np.random.randint()# random integers  
np.random.randn()  # normal (bell-curve) distribution


## Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (2, 3) → 2 rows and 3 columns
print(arr.ndim)   # Number of dimensions (2D array)
print(arr.size)   # Total number of elements (2 × 3 = 6)
print(arr.dtype)  # Data type of elements (int)


(2, 3)
2
6
int64


## Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [16]:
arr = np.array([1,2,3,4,5,6])
print(arr[1])
print(arr[2])
print(arr[-4])


2
3
3


Now lets see the 2D Indexing as well

In [17]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print(arr[0][2])
print(arr[2][1])
print(arr[1][2])


3
8
6


Now we can also do the slicing in 1D

In [18]:
a= np.array([1,2,3,4,5])
a[:2] 

array([1, 2])


Now we can also do the slicing in 2D

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr[0:2, 0:2]   #2 by 2 slice
arr[1:, 1:]

array([[5, 6],
       [8, 9]])

There is one more thing known as Boolean Indexing

In [20]:
arr = np.array([5,10,20,30,40])
print(arr>12)
print(arr[arr>12])
# Boolean indexing filters elements based on a condition (often results in 1D output)

[False False  True  True  True]
[20 30 40]


## Reshaping the Array

In [21]:
np.arange(1, 31).reshape(6, 5)  # Creates a 6×5 array with values from 1 to 30

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Flattening of an Array

In [22]:
arr.flatten()  # Converts a multi-dimensional array into a 1D array (returns a copy)


array([ 5, 10, 20, 30, 40])

## Numpy Array Operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [23]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


These things are already different from List and if we talk about one more special power it is **Broadcasting**
Broadcasting requirements:

When comparing shapes from right to left:
1-Dimensions must be equal, or
2-One of the dimensions must be 1

In [24]:
a = np.array([[1, 2, 3, 4],[5,6,7,8]])
print(a * 2)  # Multiplies each element by 2 (element-wise operation)

[[ 2  4  6  8]
 [10 12 14 16]]


## Aggregate Functions
These functions are used to calculate the Statistics on Arrays.

In [25]:
arr = np.array([4, 8, 15, 23, 56])

print(np.sum(arr))   # Sum of all elements
print(np.mean(arr))  # Average (mean)
print(np.min(arr))   # Minimum value
print(np.max(arr))   # Maximum value
print(np.std(arr))   # Standard deviation
print(np.var(arr))   # Variance


106
21.2
4
56
18.562327440275368
344.55999999999995


You can also do the axis based operations row-Wise and Colum-wise

In [26]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Sum of all:", np.sum(data))
print("Row-wise sum:", np.sum(data, axis=1))   # across columns
print("Column-wise sum:", np.sum(data, axis=0)) # across rows

print("Row-wise mean:", np.mean(data, axis=1))
print("Column-wise mean:", np.mean(data, axis=0))


Sum of all: 45
Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]
Row-wise mean: [2. 5. 8.]
Column-wise mean: [4. 5. 6.]


## Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [30]:
arr = np.array([10,20,30,40,50,60])
arr[[0,2,4]]

array([10, 30, 50])

In [56]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,1,2],[1,2,3]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 2,  7, 12])

## Conditional Selection
Find values based on conditions or replace them.

In [65]:
arr = np.array([5,12,18,7,30])
arr > 10
arr[arr>10]
np.where(arr>12,arr,0)

array([ 0,  0, 18,  0, 30])

## Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [68]:
arr = np.array([5,12,18,7,30])
arr.sort()
arr

array([ 5,  7, 12, 18, 30])

In [69]:
np.argsort(arr)

array([0, 1, 2, 3, 4])

## Concatenation and Stacking

In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [72]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [74]:
np.vstack((B,A))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [75]:
np.hstack((B,A))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [76]:
np.concat([A,B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])